# Generated by Django 3.2.14 on 2024-04-05 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0003_delete_uploadedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
